/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examinationapplication;


import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Sayyed Abrar Akhtar
 */
public class NewQuestionSetJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewQuestionSetJFrame
     */
    int operation = 0, row = 0, id;
    MySQLConnect mySqlConn;
    public NewQuestionSetJFrame() {
        initComponents();
        mySqlConn = new MySQLConnect();
        retrieveSet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldQSet = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableQSet = new javax.swing.JTable();
        jButtonAddQSet = new javax.swing.JButton();
        jButtonDelQSet = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add New Questions");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New Set Name:");

        jTextFieldQSet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTableQSet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Set ID", "Set Name"
            }
        ));
        jTableQSet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableQSetMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableQSet);

        jButtonAddQSet.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonAddQSet.setText("Add New Question Set");
        jButtonAddQSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddQSetActionPerformed(evt);
            }
        });

        jButtonDelQSet.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonDelQSet.setText("Delete");
        jButtonDelQSet.setActionCommand("Delete");
        jButtonDelQSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelQSetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addComponent(jTextFieldQSet, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAddQSet, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDelQSet, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldQSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddQSet)
                    .addComponent(jButtonDelQSet))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddQSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddQSetActionPerformed
       
        String setname = jTextFieldQSet.getText();
        if (jButtonAddQSet.getText()=="Add New Question Set"){
            addNewSet(setname);
        
        }
        if (jButtonAddQSet.getText()=="Update"){
            updateSet(setname);
        }
        retrieveSet();
    }//GEN-LAST:event_jButtonAddQSetActionPerformed

    private void jTableQSetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableQSetMouseClicked
        loadTable();
    }//GEN-LAST:event_jTableQSetMouseClicked

    private void jButtonDelQSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelQSetActionPerformed
        String setname = jButtonAddQSet.getText();
        if(jButtonAddQSet.getText()==""){
            JOptionPane.showMessageDialog(null, "please select set from table to delete!");
        } else {
            deleteSet(setname);
        }
        
    }//GEN-LAST:event_jButtonDelQSetActionPerformed

    public void loadTable(){
        
        JOptionPane.showMessageDialog(null, "Mouseclicked in table");
        operation=1;
        // code to set selected value on form
        int column = jTableQSet.getColumnCount();
        row = jTableQSet.getSelectedRow();
        JOptionPane.showMessageDialog(null, row);
        if(row>=0)
        {
          //Delete.setEnabled(true);   
        }
        id = (int) jTableQSet.getModel().getValueAt(row,0);
        String value = jTableQSet.getModel().getValueAt(row,1).toString();
        jTextFieldQSet.setText(value);
        jButtonAddQSet.setText("Update");
    
    }
    public void addNewSet(String setname){
        try{
            String query = "insert into questionset (setname) values('" + setname + "')";
            mySqlConn.executeSQLQuery(query, "New set Added Successfully!");
        } catch (Exception ex){
            System.out.println("Error in NewQuestionSetJframe at line 173: " + ex);
        }
        
    }
    
    
    
    public void retrieveSet() {
        try {
            String query = "select * from questionset";
            ResultSet resultset;
            resultset = mySqlConn.retrieveData(query);
            DefaultTableModel model = (DefaultTableModel) jTableQSet.getModel();
               while(resultset.next())
               {
                model.addRow(new Object[]{resultset.getInt("id"),resultset.getString("setname")});
               }
        } catch (Exception ex){
            System.out.println("Error in NewQuestionSetJframe at line 190: " + ex);
        }
        
    }
    
    public void updateSet(String setname){
        try {
            String query = "UPDATE `questionset` SET `setname` = '" + setname +"' WHERE `questionset`.`id` =" + id;
            mySqlConn.executeSQLQuery(query, "Setname update Successfully!");
        } catch (Exception ex){
            System.out.println("Error in NewQuestionSetJframe at line 190: " + ex);
        }
    }
    
    
    public void deleteSet(String setname){
        try {
            String query = "DELETE FROM `questionset` WHERE `questionset`.`id` =" + id;
            mySqlConn.executeSQLQuery(query, "Setname DELETED Successfully!");
        } catch (Exception ex){
            System.out.println("Error in NewQuestionSetJframe at line 190: " + ex);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewQuestionSetJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewQuestionSetJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewQuestionSetJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewQuestionSetJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewQuestionSetJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddQSet;
    private javax.swing.JButton jButtonDelQSet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableQSet;
    private javax.swing.JTextField jTextFieldQSet;
    // End of variables declaration//GEN-END:variables
}
